# TODOs
# 1) Minior improvements
#    * Add an appveyor status badge (https://www.appveyor.com/docs/status-badges/), similar to the used travis status badge
# 2) Make Eigen work
#    * Change appveyor.yml so that the library Eigen can be used on appveyor (probably, one has to make appveyor download Eigen from bitbuckets)
#    * Adapt the file cmake/FindEigen3.cmake so that the command "find_package(Eigen3 REQUIRED)" in the file CMakeLists.txt works on appveyor as well
#   * Uncomment the Eigen example in Source.cpp and let it run

os: Visual Studio 2015

platform: x64

configuration: Release
 
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

before_build:
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: build\hello.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: build\Release\hello.exe
    name: installer

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
  
  

 
