# TODOs
# 1) Minior improvements
#    * Add an appveyor status badge (https://www.appveyor.com/docs/status-badges/), similar to the used travis status badge
# 2) Make Eigen work
#    * Change appveyor.yml so that the library Eigen can be used on appveyor (probably, one has to make appveyor download Eigen from bitbuckets)
#    * Adapt the file cmake/FindEigen3.cmake so that the command "find_package(Eigen3 REQUIRED)" in the file CMakeLists.txt works on appveyor as well
##   * Uncomment the Eigen example in Source.cpp and let it run

## EIGEN CHANGS

#  The latest stable release is Eigen 3.3.3.
#   http://bitbucket.org/eigen/eigen/get/3.3.3.zip
#  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip     -OutFile eigen.zip
#  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul
#
#   Changes to  be done in CMakeLists.txt..
# http://stackoverflow.com/questions/12249140/find-package-eigen3-for-cmake
# https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html
#in before build
#   - cmd: cmake -G "Visual Studio 14 2015 Win64" -D EIGEN3_INCLUDE_DIR=C:\projects\
#  DCMAKE_MODULE_PATH=C:\projects\cmakevisualstudio\cmake\


os: Visual Studio 2015

platform: x64

configuration: Release
 
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  # To install the eigen in home directory using PowerShell
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip     -OutFile eigen.zip
  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul


before_build:
  - cmd: md build && cd build
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" ..
  - ps: ls C:/projects
  - ps: ls C:/projects/eigen-eigen-67e894c6cd8f/cmake
  - ps: ls C:/projects/eigen-eigen-67e894c6cd8f/Eigen
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" -DEIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-67e894c6cd8f\ ..
  - cmd: cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: build\hello.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: build\Release\hello.exe
    name: installer

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
  
  

 
