 # C++ Compiler
image: Visual Studio 2015

# Specify version format
#Latest
version: 1.0."{build}"


# branches to build

branches:
  only:
    - master
    
    
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2015

platform:
  - x86

configuration:
  - Release

environment:
  VS_VERSION: vs2015
  BUILD_PLATFORM: 'x32'
  DEPS_PATH: '%APPVEYOR_BUILD_FOLDER%\deps'
  LLVM_PATH: '%APPVEYOR_BUILD_FOLDER%\deps\llvm'
  BUILD_PATH: '%APPVEYOR_BUILD_FOLDER%\build\%VS_VERSION%'
  LIB_PATH: '%APPVEYOR_BUILD_FOLDER%\build\%VS_VERSION%\lib\%CONFIGURATION%_%BUILD_PLATFORM%'
  ARTIFACT_NAME: '%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%VS_VERSION%-%BUILD_PLATFORM%.zip'
#  GITHUB_ACCESS_TOKEN:
 #   secure: CrxPDgxTKC9ZRvFjttpRPO+e1DT8s0Zkk9HrAmHOIzDkOfFbbu1iTm/yJjZ2eDcd

 
 
# clone directory
clone_folder: C:\projects\cmakevisualstudio\ci  

# scripts that run after cloning repository
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  
  
build_script:

  - cd %APPVEYOR_BUILD_FOLDER%
  - dir
  # create folder for an out-of-source-tree build: "c:\projects\build"
  
  - cd.. 
  - mkdir build
  - cd build
  
  # generate build script
  - >
    cmake %APPVEYOR_BUILD_FOLDER%\src
    -G "%generator%" 
    -DCMAKE_INSTALL_PREFIX=./trials
    
  # build
  - cmake --build . --target ALL_BUILD --config %configuration% -- /nologo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
  # install
  - cmake --build . --target INSTALL --config %configuration% -- /nologo
  # package (with cpack)
  #- cmake --build ./build --target PACKAGE --config %configuration% -- /nologo
  

 # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only  
    
