 # C++ Compiler
image: Visual Studio 2015

# Specify version format
#Latest
version: 1.0."{build}"


# branches to build

branches:
  only:
    - master
    
    
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2015

platform:
  - x86

configuration:
  - Release
 
# clone directory
clone_folder: C:\projects\cmakevisualstudio\ci  

# scripts that run after cloning repository
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  
  
build_script:

  - cd %APPVEYOR_BUILD_FOLDER%
  - dir
  # create folder for an out-of-source-tree build: "c:\projects\build"
  
  - cd.. 
  - mkdir build
  - cd build
  
  # generate build script
  - >
    cmake %APPVEYOR_BUILD_FOLDER%\src
    -G "%generator%" 
    -DCMAKE_INSTALL_PREFIX=./trials
    
  # build
  project: C:\projects\cmakevisualstudio\Project1.sln  
    
    # enable MSBuild parallel builds  
    parallel: true   
    # MSBuild verbosity level (quiet|minimal|normal|detailed)  
    verbosity: normal
  

 # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only  
    
