# TODOs
# 1) Clean up and minior improvements
#    * Delete Project1.sln and add this filename to .gitignore
#    * Change the filename appveyor.yml to .appveyor.yml
#    * Let appveyor produce 64-bit builds
#    * Remove unnecessary code from appveyor.yml - which code is really needed and why is it really needed?
#    * Add an appveyor status badge (https://www.appveyor.com/docs/status-badges/), similar to the used travis status badge
# 2) Make Eigen work
#    * Change appveyor.yml so that the library Eigen can be used on appvoyer (probably, one has to make appveyor download Eigen from bitbuckets)
#    * Adapt the file cmake/FindEigen3.cmake so that the command "find_package(Eigen3 REQUIRED)" in the file CMakeLists.txt works on appveyor as well
#    * Uncomment the Eigen example in Source.cpp and let it run
# 3) Let appveyor publish the windows build to GitHub Releases (see https://www.appveyor.com/docs/deployment/github/)
#    * Use similar settings as they are used in .travis.yml

# Specify version format
#Latest
version: 1.0."{build}"


# branches to build

branches:
  only:
    - master
    
    
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2015

platform:
  - x86

configuration:
  - Release
 
# clone directory
clone_folder: C:\projects\cmakevisualstudio

# scripts that run after cloning repository
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64


  
# scripts to run before build
before_build:

  - cmd: cd C:\projects\cmakevisualstudio
  - cmd: md build
  - cmd: cd build
  
  # We generate project files for Visual Studio 12 because the boost binaries installed on the test server are for Visual Studio 12.
  - cmd: cmake -G "Visual Studio 14 2015" ..
  - cmd: ls C:/projects/cmakevisualstudio/build
  #- cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  #- cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  #- cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" -Durdfdom_DIR="%urdfdom_DIR%" -Durdfdom_headers_DIR="%urdfdom_headers_DIR%" -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..

 
build:

  project: C:\projects\cmakevisualstudio\build\hello.vcxproj # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)
